In [1]:
import os
import sys
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

# Przechodzimy do głównego folderu projektu
os.chdir(PROJECT_ROOT)

# Dodajemy src do ścieżki Pythona
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from smogcast.processing.features import build_features_from_db

print("Working directory:", Path.cwd())

Working directory: /Users/paulasopala/Documents/Praktyki/smogcast

In [2]:
df = build_features_from_db()

df.head()

,station_id,param_code,date,mean_value,max_value,coverage,pm_lag_1d,pm_mean_3d,pm_mean_7d,month,day_of_week,is_weekend,is_heating_season,target_value,temp_c,wind_ms,humidity,pressure_hpa,precip_mm
0,117,PM10,2023-08-19,26.4,26.4,4.166667,NaN,NaN,NaN,8,5,True,False,26.4,NaN,NaN,NaN,NaN,NaN
1,117,PM10,2023-08-20,18.1,18.1,4.166667,26.4,NaN,NaN,8,6,True,False,18.1,25.550000,1.466435,69.000000,NaN,0
2,117,PM10,2023-08-21,22.6,22.6,4.166667,18.1,NaN,NaN,8,0,False,False,22.6,23.308333,1.770833,76.916667,NaN,0
3,117,PM10,2023-08-22,18.7,18.7,4.166667,22.6,22.366667,NaN,8,1,False,False,18.7,22.945833,2.039352,76.708333,NaN,0
4,117,PM10,2023-08-23,24.6,24.6,4.166667,18.7,19.800000,NaN,8,2,False,False,24.6,20.800000,1.386574,69.375000,NaN,0

In [3]:
sample = df[
    (df["station_id"] == 117)
    & (df["param_code"] == "PM10")
][
    [
        "date",
        "mean_value",
        "pm_lag_1d",
        "pm_mean_3d",
        "pm_mean_7d",
    ]
].sort_values("date")

sample.head(15)

         date  mean_value  pm_lag_1d  pm_mean_3d  pm_mean_7d
0  2023-08-19        26.4        NaN         NaN         NaN
1  2023-08-20        18.1       26.4         NaN         NaN
2  2023-08-21        22.6       18.1         NaN         NaN
3  2023-08-22        18.7       22.6   22.366667         NaN
4  2023-08-23        24.6       18.7   19.800000         NaN
5  2023-08-24        22.2       24.6   21.966667         NaN
6  2023-08-25        13.5       22.2   21.833333         NaN
7  2023-08-26        10.4       13.5   20.100000   20.871429
8  2023-08-27         5.8       10.4   15.366667   18.585714
9  2023-08-28         1.0        5.8    9.900000   16.828571
10 2023-08-29         3.3        1.0    5.733333   13.742857
11 2023-08-30         9.5        3.3    3.366667   11.542857
12 2023-08-31        15.4        9.5    4.600000    9.385714
13 2023-09-01        16.5       15.4    9.400000    8.414286
14 2023-09-02        13.4       16.5   13.800000    8.842857

In [5]:
row_index = 4

previous_3 = sample.iloc[
    row_index - 3 : row_index
]["mean_value"]

print("Previous 3 values:")
print(previous_3)

print("\nManual mean:")
print(previous_3.mean())

print("\nFeature pm_mean_3d:")
print(sample.iloc[row_index]["pm_mean_3d"])

Previous 3 values:
1    18.1
2    22.6
3    18.7
Name: mean_value, dtype: float64

Manual mean:
19.8

Feature pm_mean_3d:
19.8

In [6]:
row_index = 8

previous_7 = sample.iloc[
    row_index - 7 : row_index
]["mean_value"]

print("Previous 7 values:")
print(previous_7)

print("\nManual mean:")
print(previous_7.mean())

print("\nFeature pm_mean_7d:")
print(sample.iloc[row_index]["pm_mean_7d"])

Previous 7 values:
1    18.1
2    22.6
3    18.7
4    24.6
5    22.2
6    13.5
7    10.4
Name: mean_value, dtype: float64

Manual mean:
18.585714285714285

Feature pm_mean_7d:
18.585714285714285

In [7]:
weather_check = df[
    (df["station_id"] == 117)
    & (df["param_code"] == "PM10")
][
    [
        "date",
        "target_value",
        "temp_c",
        "wind_ms",
        "humidity",
    ]
].sort_values("date")

weather_check.head(10)

        date  target_value     temp_c   wind_ms   humidity
0 2023-08-19          26.4        NaN       NaN        NaN
1 2023-08-20          18.1  25.550000  1.466435  69.000000
2 2023-08-21          22.6  23.308333  1.770833  76.916667
3 2023-08-22          18.7  22.945833  2.039352  76.708333
4 2023-08-23          24.6  20.800000  1.386574  69.375000
5 2023-08-24          22.2  21.558333  1.888889  67.166667
6 2023-08-25          13.5  24.041667  2.844907  69.000000
7 2023-08-26          10.4  23.345833  2.009259  74.541667
8 2023-08-27           5.8  20.020833  1.989583  87.541667
9 2023-08-28           1.0  17.075000  3.646991  81.875000

In [8]:
df[
    [
        "date",
        "month",
        "day_of_week",
        "is_weekend",
        "is_heating_season",
    ]
].head(10)

        date  month  day_of_week  is_weekend  is_heating_season
0 2023-08-19      8            5        True              False
1 2023-08-20      8            6        True              False
2 2023-08-21      8            0       False              False
3 2023-08-22      8            1       False              False
4 2023-08-23      8            2       False              False
5 2023-08-24      8            3       False              False
6 2023-08-25      8            4       False              False
7 2023-08-26      8            5        True              False
8 2023-08-27      8            6        True              False
9 2023-08-28      8            0       False              False